version: '3.4'

services:

  #rabbitmq:
  #  image: rabbitmq:latest
  #  container_name: rabbitmq
  #  volumes:
  #    - rabbitmqdata:/var/lib/rabbitmq
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"
  #  environment:
  #    - RABBITMQ_DEFAULT_USER=guest
  #    - RABBITMQ_DEFAULT_PASS=guest
      
  productdb:
    image: mongo
  
  basketdb:
    image: redis

  productapi:
    image: productapi
    build:
      context: .
      dockerfile: ProductManagementApi/Dockerfile
  
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: BasketAPI/Dockerfile

volumes:
  #rabbitmqdata:
  mongodata:
