version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    
  productapi:
    container_name: productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - productdb

  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports:
      - "8001:80"
    depends_on:
      - basketdb
   
