version: '3'

services:
  ms-sql-server:
    image: 'mcr.microsoft.com/mssql/server:2017-latest-ubuntu'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1434:1433"

  productmanagementapi:
    image: productmanagementapi
    build:
      context: .
      dockerfile: ProductManagementApi/Dockerfile
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "5100:80"
    depends_on:
      - ms-sql-server
    