FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build
EXPOSE 80
EXPOSE 443
WORKDIR /build

# Copy necessary files and restore as distinct layer
COPY OcelotApiGateway/OcelotApiGateway.csproj ./OcelotApiGateway/
RUN dotnet restore ./OcelotApiGateway/

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o output

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /build/output .

ENTRYPOINT [ "dotnet", "OcelotApiGateway.dll"]