FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build
WORKDIR /build

# Copy necessary files and restore as distinct layer
#COPY ls.sln ./
COPY InfrastructureLibrary/InfrastructureLibrary.csproj ./InfrastructureLibrary/
COPY ProductManagementApi/ProductManagementApi.csproj ./ProductManagementApi/
RUN dotnet restore ./ProductManagementApi/
RUN dotnet restore ./InfrastructureLibrary/



# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o output

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /build/output .

# Expose ports
EXPOSE 8100/tcp
ENV ASPNETCORE_URLS http://*:8100

ENTRYPOINT [ "dotnet", "ProductManagementApi.dll"]