version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  

  ms-sql-server:
    image: 'mcr.microsoft.com/mssql/server:2017-latest-ubuntu'
    container_name: ms-sql-server
    volumes:
      - sqlserverdata:/var/opt/mssql 
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1434:1433"

  mail:
    image: bytemark/smtp
    container_name: mail
    build:
      context: .
      dockerfile: Dockerfile_EmailNotificationService
    ports:
      - "25:25"
    depends_on:
      - rabbitmq

  ocelotapigateway:
    image: ocelotapigateway
    container_name: ocelotapigateway
    build:
      context: .
      dockerfile: Dockerfile_Ocelot
    ports:
      - "8000:8000"
    depends_on:
      - productmanagementapi
      - ms-sql-server
    
  productmanagementapi:
    image: productmanagementapi
    hostname: productmanagementapi
    container_name: productmanagementapi
    build:
      context: .
      dockerfile: Dockerfile_Product
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8100:8100"
    depends_on:
      - rabbitmq
      - ms-sql-server

  customermanagementapi:
    image: customermanagementapi
    hostname: customermanagementapi
    container_name: customermanagementapi
    build:
      context: .
      dockerfile: Dockerfile_Customer
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8200:8200"
    depends_on:
      - rabbitmq
      - ms-sql-server
  
volumes:
  rabbitmqdata:
  sqlserverdata: