FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build
WORKDIR /build

# Copy necessary files and restore as distinct layer
COPY OcelotApiGateway/OcelotApiGateway.csproj ./OcelotApiGateway/
RUN dotnet restore ./OcelotApiGateway/

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o output

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /build/output .

# Expose ports
EXPOSE 8000/tcp
ENV ASPNETCORE_URLS http://*:8000

ENTRYPOINT [ "dotnet", "OcelotApiGateway.dll"]